name: ci pipeline
on:
    pull_request:
        branches:
        - "dev"

jobs:
    build-docker:
        runs-on: ubuntu-latest

        setps:
            - name: use checkout
              uses: action/checkout@v5

            - name: check version docker
              run: |
                docker -v
                docker compose version
        

